// QueryAcountResponse
const queryAccountListResponse = [
  {
    id: "string",
    createdId: "string",
    created: 0,
    createdBy: "string",
    lastModified: 0,
    lastModifiedBy: "string",
    parentId: "string",
    hierarchialType: 0,
    dynamicPropertyValues: [
      {
        fieldConfigId: "string",
        propertyName: "string",
        value: "string",
        groupName: "string",
        isRecorded: true,
      },
    ],
    focusConfigId: "string",
    tierConfigId: "string",
    priorityConfigId: "string",
    name: "string",
    alias: "string",
    domain: "string",
    web: "string",
    email: "string",
    phone: "string",
    mobile: "string",
    functionId: "string",
    roleId: "string",
    addressLine1: "string",
    addressLine2: "string",
    postalCode: "string",
    city: "string",
    state: "string",
    countryName: "string",
    fullAddress: "string",
    overview: "string",
    executiveSummary: "string",
    relatedFundItems: [
      {
        id: "string",
        name: "string",
        email: "string",
        tagMappingMenuId: "string",
      },
    ],
    addresses: [
      {
        id: "string",
        addressLine1: "string",
        addressLine2: "string",
        postalCode: "string",
        city: "string",
        state: "string",
        accountId: "string",
        contactId: "string",
        countryName: "string",
        fullAddress: "string",
        isMain: true,
      },
    ],
    phones: [
      {
        number: "string",
        isMain: true,
      },
    ],
    mobiles: [
      {
        number: "string",
        isMain: true,
      },
    ],
  },
];

// QueryContactResponse
const queryContactListResponse = [
  {
    id: "string",
    createdId: "string",
    created: 0,
    createdBy: "string",
    lastModified: 0,
    lastModifiedBy: "string",
    parentId: "string",
    hierarchialType: 0,
    dynamicPropertyValues: [
      {
        fieldConfigId: "string",
        propertyName: "string",
        value: "string",
        groupName: "string",
        isRecorded: true,
      },
    ],
    focusConfigId: "string",
    tierConfigId: "string",
    priorityConfigId: "string",
    gender: 0,
    isPrivate: true,
    first: "string",
    last: "string",
    fullName: "string",
    domain: "string",
    web: "string",
    email: "string",
    phone: "string",
    mobile: "string",
    functionId: "string",
    roleId: "string",
    addressLine1: "string",
    addressLine2: "string",
    postalCode: "string",
    city: "string",
    state: "string",
    countryName: "string",
    fullAddress: "string",
    overview: "string",
    executiveSummary: "string",
    tagMappingMenuId: "string",
    accountId: "string",
    investmentStatusId: "string",
    relatedAccount: {
      id: "string",
      name: "string",
      email: "string",
      tagMappingMenuId: "string",
    },
    addresses: [
      {
        id: "string",
        addressLine1: "string",
        addressLine2: "string",
        postalCode: "string",
        city: "string",
        state: "string",
        accountId: "string",
        contactId: "string",
        countryName: "string",
        fullAddress: "string",
        isMain: true,
      },
    ],
    phones: [
      {
        number: "string",
        isMain: true,
      },
    ],
    mobiles: [
      {
        number: "string",
        isMain: true,
      },
    ],
  },
];

const queryFundListResponse = [
  {
    id: "string",
    createdId: "string",
    created: 0,
    createdBy: "string",
    lastModified: 0,
    lastModifiedBy: "string",
    parentId: "string",
    hierarchialType: 0,
    dynamicPropertyValues: [
      {
        fieldConfigId: "string",
        propertyName: "string",
        value: "string",
        groupName: "string",
        isRecorded: true,
      },
    ],
    focusConfigId: "string",
    tierConfigId: "string",
    priorityConfigId: "string",
    name: "string",
    alias: "string",
    domain: "string",
    sec_Type: "string",
    fund_Style: "string",
    hottie: 0,
    redFlag: 0,
    yellowFlag: 0,
    followUp: 0,
    annualReturn: 0,
    annualVolatility: 0,
    mdd: 0,
    currencyCode: "string",
    fundsSatusId: "string",
    frequencyUnitsId: "string",
    noticeUnitsId: "string",
    fatherTypesId: "string",
    investmentStatusId: "string",
    tagMappingMenuId: "string",
    overview: "string",
    executiveSummary: "string",
    externalId: "string",
    strategyId: "string",
    investmentAnalysisId: "string",
    riskAnalysisId: "string",
    liquidityInStatusId: "string",
    liquidityOutStatusId: "string",
    analysisBlobModels: [
      {
        id: "string",
        created: 0,
        domainEvents: [{}],
        contactId: "string",
        contact: {
          id: "string",
          created: 0,
          domainEvents: [{}],
          createdId: "string",
          createdBy: "string",
          lastModified: 0,
          lastModifiedBy: "string",
          deleted: true,
          parentId: "string",
          hierarchialType: 0,
          cacheKey: "string",
          dynamicPropertyValues: [
            {
              fieldConfigId: "string",
              propertyName: "string",
              value: "string",
              groupName: "string",
              isRecorded: true,
            },
          ],
          focusConfigId: "string",
          tierConfigId: "string",
          priorityConfigId: "string",
          overview: "string",
          executiveSummary: "string",
          externalId: "string",
          first: "string",
          last: "string",
          fullName: "string",
          email: "string",
          gender: 0,
          isPrivate: true,
          domain: "string",
          web: "string",
          phones: [
            {
              number: "string",
              isMain: true,
            },
          ],
          mainPhone: "string",
          mobiles: [
            {
              number: "string",
              isMain: true,
            },
          ],
          mainMobile: "string",
          addresses: [
            {
              id: "string",
              created: 0,
              domainEvents: [{}],
              addressLine1: "string",
              addressLine2: "string",
              postalCode: "string",
              city: "string",
              state: "string",
              accountId: "string",
              contactId: "string",
              countryName: "string",
              fullAddress: "string",
              isMain: true,
            },
          ],
          mainAddress: {
            id: "string",
            created: 0,
            domainEvents: [{}],
            addressLine1: "string",
            addressLine2: "string",
            postalCode: "string",
            city: "string",
            state: "string",
            accountId: "string",
            contactId: "string",
            countryName: "string",
            fullAddress: "string",
            isMain: true,
          },
          functionId: "string",
          roleId: "string",
          investmentStatusId: "string",
          tagMappingMenuId: "string",
          accountId: "string",
          analysisBlobModels: ["string"],
        },
        blobName: "string",
        timestamp: 0,
        isAnalysis: true,
      },
    ],
    relatedAccountItems: [
      {
        id: "string",
        name: "string",
        email: "string",
        tagMappingMenuId: "string",
      },
    ],
  },
];

const queryActivityListResponse = [
  {
    id: "string",
    createdId: "string",
    created: 0,
    createdBy: "string",
    lastModified: 0,
    lastModifiedBy: "string",
    parentId: "string",
    hierarchialType: 0,
    dynamicPropertyValues: [
      {
        fieldConfigId: "string",
        propertyName: "string",
        value: "string",
        groupName: "string",
        isRecorded: true,
      },
    ],
    title: "string",
    fromAddress: "string",
    toAddress: "string",
    ccAddress: "string",
    domain: "string",
    emlBlobName: "string",
    activityType: 1,
    tagMappingMenuId: "string",
    description: "string",
    comments: "string",
    contentHash: "string",
    receivedAt: 0,
    contactId: "string",
    relatedContactItem: {
      id: "string",
      name: "string",
      email: "string",
      tagMappingMenuId: "string",
    },
  },
];

const queryDocumentListResponse = [
  {
    id: "string",
    fileHash: "string",
    fileName: "string",
    blobName: "string",
    fromAddress: "string",
    toAddress: "string",
    tagConfigId: "string",
    description: "string",
  },
];
